version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - MISTRAL_API_KEY=${MISTRAL_API_KEY}
    volumes:
      - ./static:/app/static
      - ./templates:/app/templates
    restart: unless-stopped
